### ISSUE TITLE
Bot Crashes

### ISSUE THREAD

**Issue by linuxautomations** [rike422/rounders#72]
Hi,

Bot is failing with following error.

```
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1490:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1490:in `start_tls_session'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1083:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/mail-2.6.6/lib/mail/network/retriever_methods/imap.rb:157:in `new'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/mail-2.6.6/lib/mail/network/retriever_methods/imap.rb:157:in `start'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/mail-2.6.6/lib/mail/network/retriever_methods/imap.rb:74:in `find'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/receivers/mail.rb:23:in `receive'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/receivers/mail.rb:33:in `receive'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/receivers/receiver.rb:16:in `map'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/receivers/receiver.rb:16:in `receive'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/rounder.rb:73:in `receive_mail'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/rounder.rb:69:in `round'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/rounder.rb:56:in `block in polling'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/rounder.rb:55:in `loop'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rounders-0.7.3/lib/rounders/rounder.rb:55:in `polling'

```

and some times it is crashing with following error too.

```
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:57:in `sysread': Connection reset by peer (Errno::ECONNRESET)
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:57:in `fill_rbuff'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:206:in `gets'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1205:in `get_response'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1127:in `receive_responses'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1109:in `block in initialize'
```

**Comment by rike422** [comment]
Hi @linuxautomations 

Thanks for the your report.

Maybe reported error is not this library specific. 
This error related to installing Ruby.

https://stackoverflow.com/questions/40085781/error-installing-fastlane-on-project

**Comment by linuxautomations** [comment]
Thank you, it helped and also I had some issues with my code also fixed those and now it is working fine.
